import type { Handler, HandlerEvent } from "@netlify/functions";
import { GoogleGenAI } from "@google/genai";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json",
};

export const handler: Handler = async (event: HandlerEvent) => {
  if (event.httpMethod === "OPTIONS") {
    return {
      statusCode: 204,
      headers: corsHeaders,
      body: "",
    };
  }

  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      headers: corsHeaders,
      body: JSON.stringify({ error: "Method not allowed. Use POST." }),
    };
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return {
        statusCode: 500,
        headers: corsHeaders,
        body: JSON.stringify({
          error: "GEMINI_API_KEY is not configured.",
          text: "Please set GEMINI_API_KEY in your Netlify site settings (Site configuration -> Environment variables).",
        }),
      };
    }

    if (!event.body) {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ error: "Missing request body." }),
      };
    }

    const payload = JSON.parse(event.body);
    const {
      prompt,
      imageSize = "1K",
      aspectRatio = "1:1",
      model = "gemini-3-pro-image-preview",
    } = payload;

    if (!prompt || typeof prompt !== "string") {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ error: "Prompt string is required." }),
      };
    }

    const validSizes = ["1K", "2K", "4K"];
    const chosenSize = validSizes.includes(imageSize) ? imageSize : "1K";

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });

    let response;
    try {
      response = await ai.models.generateContent({
        model: model || "gemini-3-pro-image-preview",
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio || "1:1",
            imageSize: chosenSize,
          },
        },
      });
    } catch (primaryError) {
      console.warn("Primary image model failed, trying fallback...", primaryError);
      response = await ai.models.generateContent({
        model: "gemini-3.1-flash-image",
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio || "1:1",
            imageSize: chosenSize === "4K" ? "2K" : chosenSize,
          },
        },
      });
    }

    let imageUrl: string | null = null;
    let descriptionText = "";

    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData?.data) {
          const mime = part.inlineData.mimeType || "image/png";
          imageUrl = `data:${mime};base64,${part.inlineData.data}`;
        } else if (part.text) {
          descriptionText += part.text;
        }
      }
    }

    if (!imageUrl) {
      return {
        statusCode: 422,
        headers: corsHeaders,
        body: JSON.stringify({
          error: "No image was generated by the model.",
          text: descriptionText,
        }),
      };
    }

    return {
      statusCode: 200,
      headers: corsHeaders,
      body: JSON.stringify({
        imageUrl,
        text: descriptionText,
        imageSize: chosenSize,
        aspectRatio,
        prompt,
      }),
    };
  } catch (error: unknown) {
    console.error("Error in Netlify generate-image function:", error);
    const errorMessage =
      error instanceof Error ? error.message : "Failed to generate image";
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({
        error: errorMessage,
      }),
    };
  }
};
